/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RelationshipAnalysis {
    challengingAspects: Array<[string, string, string]>;
    lifeThemes: Array<string>;
    harmonicAspects: Array<[string, string, string]>;
    compatibilityScores: Array<[string, string, number]>;
}
export interface Coordinates {
    birthTimestamp: bigint;
    longMicro: bigint;
    latMicro: bigint;
}
export interface EnergyConcentration {
    retrogradePlanets: Array<string>;
    aspectPatterns: Array<[string, string]>;
    dominantCardinalModes: Array<[string, number]>;
    elementsUsage: Array<[string, number]>;
    planetsInHouses: Array<[string, number]>;
    planetsInSigns: Array<[string, number]>;
    aspectsCount: Array<[string, number]>;
}
export interface AstrologyData {
    sunSign: string;
    moonSign: string;
    aspects: Array<[string, string, string]>;
    housePositions: Array<[string, string]>;
    aspectType: string;
    ascendant: string;
    planetaryPositions: Array<[string, string]>;
}
export interface NatalAnalysis {
    signsAnalysis: Array<[string, string]>;
    planetaryPatternsAnalysis: Array<[string, string]>;
    housesAnalysis: Array<[string, string]>;
    planetaryAspectsAnalysis: Array<[string, string]>;
}
export interface PaymentSuccessResponse {
    message: string;
    payment: {
        status: string;
        paymentMethod: {
            last4: string;
            brand: string;
        };
        currency: string;
        amount: bigint;
    };
}
export interface GeneralAnalysis {
    overarchingInsights: Array<string>;
    lifeThemes: Array<string>;
    potentialGrowthAreas: Array<string>;
    personalStrengths: Array<string>;
}
export interface ReportData {
    energyConcentration: EnergyConcentration;
    chart: ChartData;
    relationshipAnalysis: RelationshipAnalysis;
    financialAnalysis: FinancialAnalysis;
    generalAnalysis: GeneralAnalysis;
    natalAnalysis: NatalAnalysis;
}
export interface GeneralReport {
    chartData: string;
    honkyChank: string;
}
export interface PaymentCancelResponse {
    message: string;
    sessionId: string;
}
export interface FinancialAnalysis {
    wealthBuildingTraits: Array<[string, string]>;
    careerPotential: Array<[string, string]>;
    financialStrategies: Array<string>;
    primaryFinancialIndicators: Array<[string, string]>;
}
export interface ChartData {
    aspects: Array<[string, string, string]>;
    housePositions: Array<[string, string]>;
    planetaryPositions: Array<[string, string]>;
    elementDistribution: Array<[string, number]>;
}
export interface UserProfile {
    birthDate?: string;
    birthTime?: string;
    name: string;
    birthPlace?: string;
    preferredReferenceChart?: string;
}
export interface CreatePaymentResponse {
    checkoutUrl: string;
    sessionId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkout(productType: string): Promise<CreatePaymentResponse>;
    findChar(input: string, charToFind: string): Promise<bigint>;
    getAllChartKeys(): Promise<Array<string>>;
    getAstrologyReport(reportId: string): Promise<AstrologyData | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChartData(reportId: string): Promise<ChartData | null>;
    getCoordinates(_reportId: string): Promise<Coordinates | null>;
    getGeneralReport(_reportId: string): Promise<GeneralReport | null>;
    getReferenceChart(chartType: string): Promise<[bigint, string] | null>;
    getReport(reportId: string): Promise<ReportData | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializePrices(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    paymentCancel(sessionId: string): Promise<PaymentCancelResponse>;
    paymentSuccess(sessionId: string, accountId: string, caffeineCustomerId: string): Promise<PaymentSuccessResponse>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { AstrologyData as _AstrologyData, ChartData as _ChartData, Coordinates as _Coordinates, GeneralReport as _GeneralReport, ReportData as _ReportData, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async checkout(arg0: string): Promise<CreatePaymentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout(arg0);
            return result;
        }
    }
    async findChar(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.findChar(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findChar(arg0, arg1);
            return result;
        }
    }
    async getAllChartKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChartKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChartKeys();
            return result;
        }
    }
    async getAstrologyReport(arg0: string): Promise<AstrologyData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAstrologyReport(arg0);
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAstrologyReport(arg0);
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getChartData(arg0: string): Promise<ChartData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChartData(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChartData(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCoordinates(arg0: string): Promise<Coordinates | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoordinates(arg0);
                return from_candid_opt_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoordinates(arg0);
            return from_candid_opt_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGeneralReport(arg0: string): Promise<GeneralReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGeneralReport(arg0);
                return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGeneralReport(arg0);
            return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getReferenceChart(arg0: string): Promise<[bigint, string] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferenceChart(arg0);
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferenceChart(arg0);
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getReport(arg0: string): Promise<ReportData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializePrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializePrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializePrices();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async paymentCancel(arg0: string): Promise<PaymentCancelResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentCancel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentCancel(arg0);
            return result;
        }
    }
    async paymentSuccess(arg0: string, arg1: string, arg2: string): Promise<PaymentSuccessResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n15(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n15(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_UserProfile_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChartData]): ChartData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coordinates]): Coordinates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeneralReport]): GeneralReport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[bigint, string]]): [bigint, string] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportData]): ReportData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AstrologyData]): AstrologyData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    birthDate: [] | [string];
    birthTime: [] | [string];
    name: string;
    birthPlace: [] | [string];
    preferredReferenceChart: [] | [string];
}): {
    birthDate?: string;
    birthTime?: string;
    name: string;
    birthPlace?: string;
    preferredReferenceChart?: string;
} {
    return {
        birthDate: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.birthDate)),
        birthTime: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.birthTime)),
        name: value.name,
        birthPlace: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.birthPlace)),
        preferredReferenceChart: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.preferredReferenceChart))
    };
}
function from_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserProfile_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n16(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    birthDate?: string;
    birthTime?: string;
    name: string;
    birthPlace?: string;
    preferredReferenceChart?: string;
}): {
    birthDate: [] | [string];
    birthTime: [] | [string];
    name: string;
    birthPlace: [] | [string];
    preferredReferenceChart: [] | [string];
} {
    return {
        birthDate: value.birthDate ? candid_some(value.birthDate) : candid_none(),
        birthTime: value.birthTime ? candid_some(value.birthTime) : candid_none(),
        name: value.name,
        birthPlace: value.birthPlace ? candid_some(value.birthPlace) : candid_none(),
        preferredReferenceChart: value.preferredReferenceChart ? candid_some(value.preferredReferenceChart) : candid_none()
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
