/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AstrologyData {
  'sunSign' : string,
  'moonSign' : string,
  'aspects' : Array<[string, string, string]>,
  'housePositions' : Array<[string, string]>,
  'aspectType' : string,
  'ascendant' : string,
  'planetaryPositions' : Array<[string, string]>,
}
export interface ChartData {
  'aspects' : Array<[string, string, string]>,
  'housePositions' : Array<[string, string]>,
  'planetaryPositions' : Array<[string, string]>,
  'elementDistribution' : Array<[string, number]>,
}
export interface Coordinates {
  'birthTimestamp' : bigint,
  'longMicro' : bigint,
  'latMicro' : bigint,
}
export interface CreatePaymentResponse {
  'checkoutUrl' : string,
  'sessionId' : string,
}
export interface EnergyConcentration {
  'retrogradePlanets' : Array<string>,
  'aspectPatterns' : Array<[string, string]>,
  'dominantCardinalModes' : Array<[string, number]>,
  'elementsUsage' : Array<[string, number]>,
  'planetsInHouses' : Array<[string, number]>,
  'planetsInSigns' : Array<[string, number]>,
  'aspectsCount' : Array<[string, number]>,
}
export interface FinancialAnalysis {
  'wealthBuildingTraits' : Array<[string, string]>,
  'careerPotential' : Array<[string, string]>,
  'financialStrategies' : Array<string>,
  'primaryFinancialIndicators' : Array<[string, string]>,
}
export interface GeneralAnalysis {
  'overarchingInsights' : Array<string>,
  'lifeThemes' : Array<string>,
  'potentialGrowthAreas' : Array<string>,
  'personalStrengths' : Array<string>,
}
export interface GeneralReport { 'chartData' : string, 'honkyChank' : string }
export interface NatalAnalysis {
  'signsAnalysis' : Array<[string, string]>,
  'planetaryPatternsAnalysis' : Array<[string, string]>,
  'housesAnalysis' : Array<[string, string]>,
  'planetaryAspectsAnalysis' : Array<[string, string]>,
}
export interface PaymentCancelResponse {
  'message' : string,
  'sessionId' : string,
}
export interface PaymentSuccessResponse {
  'message' : string,
  'payment' : {
    'status' : string,
    'paymentMethod' : { 'last4' : string, 'brand' : string },
    'currency' : string,
    'amount' : bigint,
  },
}
export interface RelationshipAnalysis {
  'challengingAspects' : Array<[string, string, string]>,
  'lifeThemes' : Array<string>,
  'harmonicAspects' : Array<[string, string, string]>,
  'compatibilityScores' : Array<[string, string, number]>,
}
export interface ReportData {
  'energyConcentration' : EnergyConcentration,
  'chart' : ChartData,
  'relationshipAnalysis' : RelationshipAnalysis,
  'financialAnalysis' : FinancialAnalysis,
  'generalAnalysis' : GeneralAnalysis,
  'natalAnalysis' : NatalAnalysis,
}
export interface UserProfile {
  'birthDate' : [] | [string],
  'birthTime' : [] | [string],
  'name' : string,
  'birthPlace' : [] | [string],
  'preferredReferenceChart' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[string], CreatePaymentResponse>,
  'findChar' : ActorMethod<[string, string], bigint>,
  'getAllChartKeys' : ActorMethod<[], Array<string>>,
  'getAstrologyReport' : ActorMethod<[string], [] | [AstrologyData]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChartData' : ActorMethod<[string], [] | [ChartData]>,
  'getCoordinates' : ActorMethod<[string], [] | [Coordinates]>,
  'getGeneralReport' : ActorMethod<[string], [] | [GeneralReport]>,
  'getReferenceChart' : ActorMethod<[string], [] | [[bigint, string]]>,
  'getReport' : ActorMethod<[string], [] | [ReportData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializePrices' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'paymentCancel' : ActorMethod<[string], PaymentCancelResponse>,
  'paymentSuccess' : ActorMethod<
    [string, string, string],
    PaymentSuccessResponse
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];