/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreatePaymentResponse = IDL.Record({
  'checkoutUrl' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const AstrologyData = IDL.Record({
  'sunSign' : IDL.Text,
  'moonSign' : IDL.Text,
  'aspects' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text)),
  'housePositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'aspectType' : IDL.Text,
  'ascendant' : IDL.Text,
  'planetaryPositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const UserProfile = IDL.Record({
  'birthDate' : IDL.Opt(IDL.Text),
  'birthTime' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'birthPlace' : IDL.Opt(IDL.Text),
  'preferredReferenceChart' : IDL.Opt(IDL.Text),
});
export const ChartData = IDL.Record({
  'aspects' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text)),
  'housePositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'planetaryPositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'elementDistribution' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
});
export const Coordinates = IDL.Record({
  'birthTimestamp' : IDL.Int,
  'longMicro' : IDL.Int,
  'latMicro' : IDL.Int,
});
export const GeneralReport = IDL.Record({
  'chartData' : IDL.Text,
  'honkyChank' : IDL.Text,
});
export const EnergyConcentration = IDL.Record({
  'retrogradePlanets' : IDL.Vec(IDL.Text),
  'aspectPatterns' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'dominantCardinalModes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
  'elementsUsage' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
  'planetsInHouses' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
  'planetsInSigns' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
  'aspectsCount' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
});
export const RelationshipAnalysis = IDL.Record({
  'challengingAspects' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text)),
  'lifeThemes' : IDL.Vec(IDL.Text),
  'harmonicAspects' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text)),
  'compatibilityScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat8)),
});
export const FinancialAnalysis = IDL.Record({
  'wealthBuildingTraits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'careerPotential' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'financialStrategies' : IDL.Vec(IDL.Text),
  'primaryFinancialIndicators' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const GeneralAnalysis = IDL.Record({
  'overarchingInsights' : IDL.Vec(IDL.Text),
  'lifeThemes' : IDL.Vec(IDL.Text),
  'potentialGrowthAreas' : IDL.Vec(IDL.Text),
  'personalStrengths' : IDL.Vec(IDL.Text),
});
export const NatalAnalysis = IDL.Record({
  'signsAnalysis' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'planetaryPatternsAnalysis' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'housesAnalysis' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'planetaryAspectsAnalysis' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const ReportData = IDL.Record({
  'energyConcentration' : EnergyConcentration,
  'chart' : ChartData,
  'relationshipAnalysis' : RelationshipAnalysis,
  'financialAnalysis' : FinancialAnalysis,
  'generalAnalysis' : GeneralAnalysis,
  'natalAnalysis' : NatalAnalysis,
});
export const PaymentCancelResponse = IDL.Record({
  'message' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const PaymentSuccessResponse = IDL.Record({
  'message' : IDL.Text,
  'payment' : IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func([IDL.Text], [CreatePaymentResponse], []),
  'findChar' : IDL.Func([IDL.Text, IDL.Text], [IDL.Int], ['query']),
  'getAllChartKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAstrologyReport' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AstrologyData)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChartData' : IDL.Func([IDL.Text], [IDL.Opt(ChartData)], ['query']),
  'getCoordinates' : IDL.Func([IDL.Text], [IDL.Opt(Coordinates)], ['query']),
  'getGeneralReport' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GeneralReport)],
      ['query'],
    ),
  'getReferenceChart' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Tuple(IDL.Int, IDL.Text))],
      ['query'],
    ),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(ReportData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializePrices' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
  'paymentSuccess' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PaymentSuccessResponse],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreatePaymentResponse = IDL.Record({
    'checkoutUrl' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const AstrologyData = IDL.Record({
    'sunSign' : IDL.Text,
    'moonSign' : IDL.Text,
    'aspects' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text)),
    'housePositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'aspectType' : IDL.Text,
    'ascendant' : IDL.Text,
    'planetaryPositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const UserProfile = IDL.Record({
    'birthDate' : IDL.Opt(IDL.Text),
    'birthTime' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'birthPlace' : IDL.Opt(IDL.Text),
    'preferredReferenceChart' : IDL.Opt(IDL.Text),
  });
  const ChartData = IDL.Record({
    'aspects' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text)),
    'housePositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'planetaryPositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'elementDistribution' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
  });
  const Coordinates = IDL.Record({
    'birthTimestamp' : IDL.Int,
    'longMicro' : IDL.Int,
    'latMicro' : IDL.Int,
  });
  const GeneralReport = IDL.Record({
    'chartData' : IDL.Text,
    'honkyChank' : IDL.Text,
  });
  const EnergyConcentration = IDL.Record({
    'retrogradePlanets' : IDL.Vec(IDL.Text),
    'aspectPatterns' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'dominantCardinalModes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
    'elementsUsage' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
    'planetsInHouses' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
    'planetsInSigns' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
    'aspectsCount' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
  });
  const RelationshipAnalysis = IDL.Record({
    'challengingAspects' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text)),
    'lifeThemes' : IDL.Vec(IDL.Text),
    'harmonicAspects' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text)),
    'compatibilityScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat8)),
  });
  const FinancialAnalysis = IDL.Record({
    'wealthBuildingTraits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'careerPotential' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'financialStrategies' : IDL.Vec(IDL.Text),
    'primaryFinancialIndicators' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const GeneralAnalysis = IDL.Record({
    'overarchingInsights' : IDL.Vec(IDL.Text),
    'lifeThemes' : IDL.Vec(IDL.Text),
    'potentialGrowthAreas' : IDL.Vec(IDL.Text),
    'personalStrengths' : IDL.Vec(IDL.Text),
  });
  const NatalAnalysis = IDL.Record({
    'signsAnalysis' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'planetaryPatternsAnalysis' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'housesAnalysis' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'planetaryAspectsAnalysis' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const ReportData = IDL.Record({
    'energyConcentration' : EnergyConcentration,
    'chart' : ChartData,
    'relationshipAnalysis' : RelationshipAnalysis,
    'financialAnalysis' : FinancialAnalysis,
    'generalAnalysis' : GeneralAnalysis,
    'natalAnalysis' : NatalAnalysis,
  });
  const PaymentCancelResponse = IDL.Record({
    'message' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const PaymentSuccessResponse = IDL.Record({
    'message' : IDL.Text,
    'payment' : IDL.Record({
      'status' : IDL.Text,
      'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
      'currency' : IDL.Text,
      'amount' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func([IDL.Text], [CreatePaymentResponse], []),
    'findChar' : IDL.Func([IDL.Text, IDL.Text], [IDL.Int], ['query']),
    'getAllChartKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAstrologyReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AstrologyData)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChartData' : IDL.Func([IDL.Text], [IDL.Opt(ChartData)], ['query']),
    'getCoordinates' : IDL.Func([IDL.Text], [IDL.Opt(Coordinates)], ['query']),
    'getGeneralReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GeneralReport)],
        ['query'],
      ),
    'getReferenceChart' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Tuple(IDL.Int, IDL.Text))],
        ['query'],
      ),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(ReportData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializePrices' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
    'paymentSuccess' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PaymentSuccessResponse],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };